language: ruby
cache: bundler

rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - 2.4.1
  - 2.5
  - ruby-head

before_install: travis_retry gem update --system

bundler_args: --without development --retry=3 --jobs=3

script: bundle exec rake
